import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { NullEngine } from '@babylonjs/core/Engines/nullEngine.js';
import { Scene } from '@babylonjs/core/scene.js';
import { ImportMeshAsync } from '@babylonjs/core/Loading/sceneLoader.js';
import '@babylonjs/loaders/glTF/2.0/glTFLoader.js';
import '@babylonjs/loaders/glTF/glTFFileLoader.js';
const scene = new Scene(new NullEngine());
const asset = await ImportMeshAsync(new Uint8Array(readFileSync('public/models/warrior.glb')),scene,{pluginExtension:'.glb'});
console.log('groups',asset.animationGroups.map(g=>[g.name,g.from,g.to,g.targetedAnimations.length]));
const bone = asset.transformNodes.find(n=>n.name==='DEF-upper_arm.L');
const rest=bone.rotationQuaternion.clone();
scene.useConstantAnimationDeltaTime=true;
for (const group of asset.animationGroups) group.stop();
for (const group of asset.animationGroups) { group.enableBlending=false; group.weight=group.name==='Idle'?1:0; group.start(true); }
for(let i=0;i<30;i++) scene._animate();
const idle=bone.rotationQuaternion.clone();
assert.ok(!idle.equalsWithEpsilon(rest,.05),'Idle must lower the arm from its bind pose');
for (const group of asset.animationGroups) group.setWeightForAllAnimatables(group.name==='Run'?1:0);
for(let i=0;i<10;i++) scene._animate();
const run=bone.rotationQuaternion.clone();
assert.ok(!run.equalsWithEpsilon(idle,.03),'Run must move the arm');
const knee=asset.transformNodes.find(n=>n.name==='DEF-shin.L');
const first=knee.rotationQuaternion.clone();
for(let i=0;i<8;i++) scene._animate();
assert.ok(!knee.rotationQuaternion.equalsWithEpsilon(first,.03),'Run must articulate the knee');
asset.skeletons[0].prepare();
assert.ok([...asset.skeletons[0].getTransformMatrices(asset.meshes.find(m=>m.skeleton))].every(Number.isFinite));
assert.equal(asset.skeletons[0].bones.length,23);
assert.deepEqual(asset.animationGroups.map(g=>g.name),['Idle','Run','Boost','Ascend','Fall']);
console.log('warrior skeleton and animation load passed');
scene.dispose();
